export const SYSTEM_SET_CONFIG = "SYSTEM_SET_CONFIG";
export const SYSTEM_LOADER_START = 'SYSTEM_LOADER_START';
export const SYSTEM_LOADER_STOP = 'SYSTEM_LOADER_STOP';
export const SYSTEM_LOADER_PROGRESS = 'SYSTEM_LOADER_PROGRESS';

